# Generated by Django 5.2.4 on 2025-07-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.CharField(default='', max_length=10, verbose_name='Артикул'),
        ),
    ]
