# Generated by Django 5.2.4 on 2025-07-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_article'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_id_a44864_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(default='', max_length=10, unique=True, verbose_name='Артикул'),
        ),
    ]
