# Generated by Django 5.2.4 on 2025-07-30 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_catalog_pro_id_a44864_idx_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lead',
            new_name='OrderCallBack',
        ),
    ]
