# Generated by Django 5.2.4 on 2025-08-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_lead_ordercallback'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bulk_only',
            field=models.BooleanField(default=False, verbose_name='Только оптом (упаковкой по X штук)'),
        ),
        migrations.AddField(
            model_name='product',
            name='bulk_quantity',
            field=models.PositiveIntegerField(default=1000, verbose_name='Кратность упаковки'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('шт', 'Штуки'), ('к-т', 'Комплекты'), ('упак', 'Упаковки'), ('метр', 'Метры'), ('кг', 'Килограммы')], default='шт', max_length=10, verbose_name='Единица измерения'),
        ),
    ]
